version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "${NEW_TASK_DEF_ARN}"
        LoadBalancerInfo:
          ContainerName: "my-node-app"
          ContainerPort: 3000